/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "./test_SR_preamble.sas" /nosource;
/* Remove all output files. */
%cleandir(., tex, tex);
%cleandir(., png, png);
%cleandir(., lst, lst);


/* Start program with a null title. */
title;

data rats;
  infile '/folders/myfolders/jumping.txt' firstobs=2;
  input group $ density;

%output(aa)
proc means;
  var density;
  class group;

%endoutput(aa)

%write(aaa,store=aa,type=listing) 

%output(ab)
proc sgplot;
  vbox density / category=group;
  
%endoutput(ab)

%write(abb,store=ab,type=graphic) 

